import Head from 'next/head';
import Image from 'next/image';
import TopTracks from '../components/TopTracks';
import NowPlaying from '../components/NowPlaying';
import Hero from '../components/Hero';
import clsx from 'clsx';

import styles from '../styles/Home.module.scss';
import Navbar from '@components/Navbar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Adarsh Sulegai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div id="about">
        <Hero />
        <Hero />
        <TopTracks />
      </div>

      <div className={styles.nowPlaying}>
        <NowPlaying />
      </div>
      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
}
