import Head from 'next/head';
import Image from 'next/image';
import TopTracks from '../components/TopTracks';
import NowPlaying from '../components/NowPlaying';
import Hero from '../components/Hero';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Adarsh Sulegai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bk}>
        <Hero />
        <TopTracks />
        <div className={styles.nowPlaying}>
          <NowPlaying />
        </div>
      </div>
      <footer className={styles.footer}></footer>
    </div>
  );
}
