import Head from 'next/head';
import Image from 'next/image';
import TopTracks from '../components/TopTracks';
import NowPlaying from '../components/NowPlaying';
import Hero from '../components/Hero';
import clsx from 'clsx';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Adarsh Sulegai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        className={clsx(
          styles.navbar,
          'rounded-full bg-gradient-to-r dark:from-rose-700 dark:via-pink-700 dark:to-purple-700 dark:opacity-60 from-blue-300 via-cyan-300 to-green-300 opacity-70 -z5 aspect-square w-full max-w-screen-lg blur-3xl filter bottom-[calc(100%-200px)] dark:bottom-[calc(100%-180px)] '
        )}
      >
        <li>Home</li>
        <li>About me</li>
        <li>Work</li>
        <li>More</li>
      </nav>
      <div className="">
        <Hero />
        {/* <TopTracks /> */}
        <div className={styles.nowPlaying}>
          <NowPlaying />
        </div>
      </div>
      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
}
